#!/usr/bin/env bash

set -e

sudo apt update && sudo apt install -y \
  locales \
  nano \
  rsync \
  git \
  wget \
  curl \
  openssh-server \
  xorg \
  net-tools \
  unzip \
  tree \
  tmuxinator

#Set locale
sudo locale-gen en_US.UTF-8
sudo update-locale LANG=en_US.UTF-8

#Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

#Install node
nvm install node 

#Install uv
curl -LsSf https://astral.sh/uv/install.sh | bash

#Set tmuxinator config
echo 'alias mux="tmuxinator"' >> ~/.bashrc
echo 'alias setmux="export TMUXINATOR_CONFIG=\$PWD"' >> ~/.bashrc
[ ! -d ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cp tmux.conf $HOME/.tmux.conf

# Install Gemini
npm install -g @google/gemini-cli

# Install OpenCode
curl -fsSL https://opencode.ai/install | bash

# Install Claude Code
curl -fsSL https://claude.ai/install.sh | bash

# Install Glow MD viewer
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install glow

# Install OMSH
sudo apt-get update
sudo apt-get install -y locales
sudo locale-gen en_SG.UTF-8
sudo update-locale LANG=en_SG.UTF-8
git clone https://github.com/ohmybash/oh-my-bash.git ~/.oh-my-bash

cat >> ~/.bashrc << 'EOF'
# Oh My Bash
export OSH="$HOME/.oh-my-bash"
OSH_THEME="vscode"
source "$OSH/oh-my-bash.sh"
EOF

echo "INSTALLATION DONE!"
