#!/usr/bin/env bash

set -e

sudo apt update && sudo apt install -y \
  nano \
  rsync \
  git \
  wget \
  curl \
  openssh-server \
  xorg \
  net-tools \
  unzip \
  tmuxinator


#Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

#Install node
nvm install node 

#Install uv
curl -LsSf https://astral.sh/uv/install.sh | bash

#Set tmuxinator config
echo 'alias mux="tmuxinator"' >> ~/.bashrc
echo 'alias setmux="export TMUXINATOR_CONFIG=\$PWD"' >> ~/.bashrc
[ ! -d ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cp tmux.conf $HOME/.tmux.conf

# Install Gemini
npm install -g @google/gemini-cli

# Install OpenCode
curl -fsSL https://opencode.ai/install | bash

# Install Glow MD viewer
sudo snap install glow

echo "INSTALLATION DONE!"
