#!/usr/bin/env bash

set -e

#Install curl
sudo apt update && sudo apt install -y curl

# Install Docker
curl -sSL https://get.docker.com | sudo sh
sudo usermod -aG docker $USER
newgrp docker <<EONG
echo "Docker Will Restart..."
EONG
sudo systemctl restart docker

# Install Nvidia Runtime
if lspci | grep -i nvidia > /dev/null; then
    echo "NVIDIA GPU detected. Installing NVIDIA container runtime..."
    # Ref: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list 

    sudo apt update && sudo apt install -y nvidia-container-toolkit
    sudo nvidia-ctk runtime configure --runtime=docker --set-as-default
    sudo systemctl daemon-reload && sudo systemctl restart docker
else
    echo "No NVIDIA GPU detected. Skipping NVIDIA container runtime installation."
fi

echo "INSTALLATION DONE!"
