#!/usr/bin/env bash

set -e

GAZEBO_CONFIG_DIR=$(dirname "$(readlink -f "$0")")

export PATH="$PATH:$HOME/miniconda3/bin"

cd $HOME
sudo rm -rf /tmp/sophus
sudo rm -rf gym-gazebo
sudo rm -rf Theano
conda env remove --name openai-gym --yes 

# Create conda environment
conda create --name openai-gym pip python=3 --yes
source $HOME/miniconda3/bin/activate openai-gym

# Install python dependencies
yes | pip install numpy \
catkin_pkg \
rospkg \
gym \
matplotlib \
h5py \
pyyaml \
scikit-image \
netifaces \
defusedxml \
opencv-python \
keras 

conda install -n openai-gym \
defusedxml \
pyqt \
tensorflow-gpu \
--yes 

# Install ROS Kinetic dependencies
sudo apt-get -y install \
cmake gcc g++ qt4-qmake libqt4-dev \
libusb-dev libftdi-dev python-vcstool \
ros-kinetic-octomap-msgs \
ros-kinetic-joy \
ros-kinetic-geodesy \
ros-kinetic-octomap-ros \
ros-kinetic-control-toolbox \
ros-kinetic-pluginlib \
ros-kinetic-trajectory-msgs \
ros-kinetic-control-msgs \
ros-kinetic-std-srvs \
ros-kinetic-nodelet \
ros-kinetic-urdf \
ros-kinetic-rviz \
ros-kinetic-kdl-conversions \
ros-kinetic-eigen-conversions \
ros-kinetic-tf2-sensor-msgs \
ros-kinetic-pcl-ros \
ros-kinetic-navigation \
ros-kinetic-ar-track-alvar \
ros-kinetic-rqt-robot-dashboard \
ros-kinetic-rqt-plot

# Install Gazebo
# sudo apt-get remove ros-kinetic-gazebo* 
# sudo apt-get upgrade
# sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
# wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
# sudo apt-get update
# sudo apt-get -y install ros-kinetic-gazebo8*

sudo apt-get -y install \
libspnav-dev \
libbluetooth-dev \
libcwiid-dev \
pyqt4-dev-tools \
libusb-dev

# Download and install Gazebo gym
cd $HOME
git clone https://github.com/erlerobot/gym-gazebo
cd gym-gazebo
yes | pip install -e .

# Install Sophus
cd /tmp
git clone https://github.com/stonier/sophus -b release/0.9.1-kinetic
cd sophus
mkdir build
cd build
cmake ..
make
sudo make install

# Install Theano
cd $HOME
git clone git://github.com/Theano/Theano.git
cd Theano/
python setup.py develop

source $HOME/miniconda3/bin/deactivate
cd $HOME/gym-gazebo/gym_gazebo/envs/installation
cp -r $GAZEBO_CONFIG_DIR/*.patch .
patch < gazebo_repos.patch
patch < setup_kinetic.patch
bash setup_kinetic.bash

echo "alias gym_ws=\"source $HOME/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/devel/setup.bash && source $HOME/miniconda3/bin/activate openai-gym\"" >> $HOME/.bashrc
# cd /opt/ros/kinetic/lib/python2.7/dist-packages/ && sudo mv cv2.so cv2_old.so