#!/usr/bin/env bash

set -e

GAZEBO_CONFIG_DIR=$(dirname "$(readlink -f "$0")")

export PATH="$PATH:$HOME/miniconda3/bin"

cd $HOME
sudo rm -rf /tmp/sophus
sudo rm -rf gym-gazebo
sudo rm -rf Theano
conda env remove --name openai-gym --yes 

# Create conda environment
conda create --name openai-gym pip python=3.5 --yes
source $HOME/miniconda3/bin/activate openai-gym

# Install python dependencies
yes | pip install \
numpy \
catkin_pkg \
rospkg \
gym \
matplotlib \
h5py \
pyyaml \
scikit-image \
netifaces \
defusedxml \
vcstool \
keras \
tf-nightly-gpu

conda install -n openai-gym \
opencv \
defusedxml \
pyqt boost \
--yes 

# Install ROS Kinetic dependencies
sudo apt-get -y install \
cmake gcc g++ qt4-qmake libqt4-dev \
libusb-dev libftdi-dev \
ros-kinetic-octomap-msgs \
ros-kinetic-joy \
ros-kinetic-geodesy \
ros-kinetic-octomap-ros \
ros-kinetic-control-toolbox \
ros-kinetic-pluginlib \
ros-kinetic-trajectory-msgs \
ros-kinetic-control-msgs \
ros-kinetic-std-srvs \
ros-kinetic-nodelet \
ros-kinetic-urdf \
ros-kinetic-rviz \
ros-kinetic-kdl-conversions \
ros-kinetic-eigen-conversions \
ros-kinetic-tf2-sensor-msgs \
ros-kinetic-pcl-ros \
ros-kinetic-navigation \
ros-kinetic-ar-track-alvar \
ros-kinetic-mav-msgs \
ros-kinetic-rqt-robot-dashboard \ 
ros-kinetic-rqt-plot

sudo apt-get -y install libspnav-dev libbluetooth-dev libcwiid-dev pyqt4-dev-tools

# Install Sophus
cd /tmp
git clone https://github.com/stonier/sophus -b release/0.9.1-kinetic
cd sophus
mkdir build
cd build
cmake ..
make
sudo make install

# Download and install Gazebo gym
cd $HOME
git clone https://github.com/erlerobot/gym-gazebo
cd gym-gazebo
pip install -e .

# Install Theano
cd $HOME
git clone git://github.com/Theano/Theano.git
cd Theano/
python setup.py develop

cd $HOME/gym-gazebo/gym_gazebo/envs/installation
cp $GAZEBO_CONFIG_DIR/gazebo.repos .
bash setup_$ROS_DISTRO.bash
