#!/usr/bin/env bash

NVIDIA_DRIVER=525

set -e

sudo apt update && sudo apt install -y \
  git \
  wget \
  curl \
  openssh-server \
  xorg \
  net-tools

# Install Docker
curl -sSL https://get.docker.com | sudo sh
sudo usermod -aG docker $USER
newgrp docker <<EONG
echo "Docker Will Restart..."
EONG
sudo systemctl restart docker

# Install Nvidia Runtime
# Ref: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
  sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
  sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list 

sudo apt update && sudo apt install -y nvidia-container-toolkit
sudo nvidia-ctk runtime configure --runtime=docker --set-as-default
sudo systemctl daemon-reload && sudo systemctl restart docker

echo "INSTALLATION DONE!"
